import type { Workspace } from './types';

export const initialWorkspace: Workspace = {
  currentUser: {
    id: 'ava-khan',
    name: 'Ava Khan',
    initials: 'AK',
    email: 'ava.khan@bremmar.example',
    role: 'TeamLead',
    accent: '#007E32',
  },
  quarter: {
    id: '2026-q3',
    label: 'Q3 2026',
    theme: 'Make Q3 feel lighter.',
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    daysRemaining: 31,
  },
  teams: [
    {
      id: 'leadership',
      name: 'Leadership Team',
      shortName: 'Leadership',
      description: 'The company-wide operating rhythm and cross-functional priorities.',
      memberCount: 7,
      meetingDay: 'Monday',
      meetingTime: '9:00 AM',
      accent: '#007E32',
      initials: 'LT',
    },
    {
      id: 'delivery',
      name: 'Delivery & Operations',
      shortName: 'Delivery',
      description: 'Making the client experience predictable, calm, and repeatable.',
      memberCount: 9,
      meetingDay: 'Tuesday',
      meetingTime: '10:30 AM',
      accent: '#4c8f86',
      initials: 'DO',
    },
    {
      id: 'growth',
      name: 'Growth',
      shortName: 'Growth',
      description: 'Creating a healthy pipeline and a clear story in the market.',
      memberCount: 6,
      meetingDay: 'Wednesday',
      meetingTime: '11:00 AM',
      accent: '#6b63ad',
      initials: 'GR',
    },
  ],
  rocks: [
    {
      id: 'rock-playbook',
      teamId: 'leadership',
      title: 'Launch the client onboarding playbook',
      description: 'One clear path from signed agreement to first value for every new client.',
      ownerId: 'ava-khan',
      status: 'on-track',
      progress: 72,
      milestonesDone: 4,
      milestonesTotal: 5,
      dueDate: 'Sep 30',
      priority: 'high',
    },
    {
      id: 'rock-cycle',
      teamId: 'leadership',
      title: 'Reduce average onboarding time to 10 days',
      description: 'Remove the handoff friction that keeps new customers waiting.',
      ownerId: 'marcus-lee',
      status: 'on-track',
      progress: 64,
      milestonesDone: 3,
      milestonesTotal: 5,
      dueDate: 'Sep 30',
      priority: 'high',
    },
    {
      id: 'rock-ops-lead',
      teamId: 'leadership',
      title: 'Hire and onboard a senior operations lead',
      description: 'Find the right seat owner to give the operating system more lift.',
      ownerId: 'priya-shah',
      status: 'off-track',
      progress: 45,
      milestonesDone: 2,
      milestonesTotal: 5,
      dueDate: 'Sep 20',
      priority: 'high',
    },
    {
      id: 'rock-soc2',
      teamId: 'leadership',
      title: 'Complete SOC 2 readiness sprint',
      description: 'Close the remaining evidence and process gaps before the audit window.',
      ownerId: 'daniel-cho',
      status: 'complete',
      progress: 100,
      milestonesDone: 5,
      milestonesTotal: 5,
      dueDate: 'Sep 12',
      priority: 'medium',
    },
    {
      id: 'rock-delivery-template',
      teamId: 'delivery',
      title: 'Standardise the implementation kickoff',
      description: 'Give every project the same calm, prepared first week.',
      ownerId: 'maria-ortiz',
      status: 'on-track',
      progress: 58,
      milestonesDone: 3,
      milestonesTotal: 5,
      dueDate: 'Sep 30',
      priority: 'high',
    },
    {
      id: 'rock-growth-pipeline',
      teamId: 'growth',
      title: 'Build a qualified pipeline worth 2.5m',
      description: 'Make the next quarter visible early enough to make good decisions.',
      ownerId: 'jon-bell',
      status: 'on-track',
      progress: 67,
      milestonesDone: 4,
      milestonesTotal: 6,
      dueDate: 'Sep 30',
      priority: 'high',
    },
  ],
  todos: [
    {
      id: 'todo-brief',
      teamId: 'leadership',
      title: 'Share the revised Q4 planning brief with leadership',
      ownerId: 'ava-khan',
      dueDate: 'Today',
      status: 'open',
      origin: 'Leadership L10 · Aug 24',
      isMine: true,
    },
    {
      id: 'todo-handoff',
      teamId: 'leadership',
      title: 'Schedule the customer success / delivery handoff',
      ownerId: 'ava-khan',
      dueDate: 'Tomorrow',
      status: 'open',
      origin: 'Issue · Onboarding handoffs',
      isMine: true,
    },
    {
      id: 'todo-alerts',
      teamId: 'leadership',
      title: 'Confirm Azure cost alerts with DevOps',
      ownerId: 'daniel-cho',
      dueDate: 'Aug 31',
      status: 'done',
      origin: 'Leadership L10 · Aug 24',
    },
    {
      id: 'todo-feedback',
      teamId: 'leadership',
      title: 'Review onboarding playbook feedback from Maya',
      ownerId: 'ava-khan',
      dueDate: 'Sep 1',
      status: 'open',
      origin: 'Rock · Client onboarding playbook',
      isMine: true,
    },
    {
      id: 'todo-scorecard',
      teamId: 'leadership',
      title: 'Publish the Friday scorecard update',
      ownerId: 'marcus-lee',
      dueDate: 'Sep 4',
      status: 'open',
      origin: 'Leadership L10 · Aug 24',
    },
    {
      id: 'todo-review',
      teamId: 'leadership',
      title: 'Review the after-hours escalation draft',
      ownerId: 'ava-khan',
      dueDate: 'Sep 2',
      status: 'not-done',
      origin: 'Issue · Customer escalation path',
      isMine: true,
    },
    {
      id: 'todo-delivery',
      teamId: 'delivery',
      title: 'Pilot the new implementation kickoff checklist',
      ownerId: 'maria-ortiz',
      dueDate: 'Sep 2',
      status: 'open',
      origin: 'Delivery L10 · Aug 25',
    },
    {
      id: 'todo-growth',
      teamId: 'growth',
      title: 'Qualify the top five expansion opportunities',
      ownerId: 'jon-bell',
      dueDate: 'Sep 3',
      status: 'open',
      origin: 'Growth L10 · Aug 26',
    },
  ],
  issues: [
    {
      id: 'issue-handoffs',
      teamId: 'leadership',
      title: 'Onboarding handoffs still rely on tribal knowledge',
      detail: 'The team is solving the same handoff questions in three different places. We need one owner, one checklist, and one visible path.',
      category: 'Process',
      priority: 1,
      status: 'open',
      raisedById: 'ava-khan',
      age: '2 weeks',
      linkedRockId: 'rock-playbook',
      idsNote: 'Identify the exact moment the handoff becomes ambiguous, then decide who owns the customer-facing transition.',
    },
    {
      id: 'issue-planning',
      teamId: 'leadership',
      title: 'The quarterly planning template arrives too late for team leads',
      detail: 'Teams are committing to Rocks before they can see the company-level constraints and focus areas.',
      category: 'Alignment',
      priority: 2,
      status: 'open',
      raisedById: 'marcus-lee',
      age: '5 days',
      idsNote: 'Decide what information must be available before each team starts quarterly planning.',
    },
    {
      id: 'issue-escalation',
      teamId: 'leadership',
      title: 'Customer escalation path is unclear after hours',
      detail: 'A recent customer concern sat overnight because nobody knew who had the next call.',
      category: 'Customer',
      priority: 3,
      status: 'in-ids',
      raisedById: 'priya-shah',
      age: '3 days',
      idsNote: 'We have agreement on the first-response owner. The open decision is who acts as backup and where the rota lives.',
    },
    {
      id: 'issue-renewal',
      teamId: 'leadership',
      title: 'Renewal risk review needs a single owner',
      detail: 'The team now has a clear Friday review and an accountable owner for every at-risk account.',
      category: 'Customer',
      priority: 4,
      status: 'solved',
      raisedById: 'ava-khan',
      age: '1 week',
    },
    {
      id: 'issue-delivery',
      teamId: 'delivery',
      title: 'Implementation scope changes are not visible early enough',
      detail: 'The delivery team needs a consistent signal when a project starts to drift from the agreed scope.',
      category: 'Delivery',
      priority: 1,
      status: 'open',
      raisedById: 'maria-ortiz',
      age: '1 week',
    },
    {
      id: 'issue-growth',
      teamId: 'growth',
      title: 'Marketing and sales use different definitions of qualified',
      detail: 'The pipeline number is healthy, but the team does not agree on the quality bar behind it.',
      category: 'Alignment',
      priority: 1,
      status: 'open',
      raisedById: 'jon-bell',
      age: '4 days',
    },
  ],
  metrics: [
    {
      id: 'metric-pipeline',
      teamId: 'leadership',
      label: 'Qualified pipeline created',
      target: '18',
      actual: '21',
      unit: 'opportunities',
      ownerId: 'jon-bell',
      status: 'on-track',
      trend: 'up',
      trendLabel: '+3 vs last week',
    },
    {
      id: 'metric-onboarding',
      teamId: 'leadership',
      label: 'Average onboarding cycle',
      target: '10',
      actual: '12',
      unit: 'days',
      ownerId: 'marcus-lee',
      status: 'off-track',
      trend: 'down',
      trendLabel: '+1 day vs last week',
    },
    {
      id: 'metric-health',
      teamId: 'leadership',
      label: 'Customer health checks',
      target: '15',
      actual: '17',
      unit: 'checks',
      ownerId: 'priya-shah',
      status: 'on-track',
      trend: 'up',
      trendLabel: '+4 vs last week',
    },
    {
      id: 'metric-incidents',
      teamId: 'leadership',
      label: 'Critical incidents',
      target: '< 2',
      actual: '1',
      unit: 'incidents',
      ownerId: 'daniel-cho',
      status: 'on-track',
      trend: 'flat',
      trendLabel: 'Holding steady',
    },
    {
      id: 'metric-kickoffs',
      teamId: 'delivery',
      label: 'Projects kicked off on time',
      target: '90%',
      actual: '94%',
      unit: 'on-time',
      ownerId: 'maria-ortiz',
      status: 'on-track',
      trend: 'up',
      trendLabel: '+6 pts vs last week',
    },
    {
      id: 'metric-discovery',
      teamId: 'growth',
      label: 'Qualified discovery calls',
      target: '12',
      actual: '9',
      unit: 'calls',
      ownerId: 'jon-bell',
      status: 'off-track',
      trend: 'down',
      trendLabel: '-2 vs last week',
    },
  ],
  headlines: [
    {
      id: 'headline-win',
      teamId: 'leadership',
      authorId: 'priya-shah',
      type: 'win',
      title: 'Aster renewed for another year',
      detail: 'The new executive review landed well and gave us a strong expansion conversation.',
      createdAt: 'Today · 8:20 AM',
    },
    {
      id: 'headline-concern',
      teamId: 'leadership',
      authorId: 'marcus-lee',
      type: 'concern',
      title: 'Two new clients waited on access setup',
      detail: 'Both were resolved, but the pattern suggests our first-day checklist is still too loose.',
      createdAt: 'Yesterday · 4:10 PM',
      issueId: 'issue-handoffs',
    },
    {
      id: 'headline-delivery',
      teamId: 'delivery',
      authorId: 'maria-ortiz',
      type: 'win',
      title: 'The Redwood kickoff was our smoothest yet',
      detail: 'The pre-read and decision log made the first meeting feel effortless.',
      createdAt: 'Yesterday · 3:45 PM',
    },
    {
      id: 'headline-growth',
      teamId: 'growth',
      authorId: 'jon-bell',
      type: 'concern',
      title: 'The qualified pipeline definition is creating noise',
      detail: 'We should agree on one definition before the next forecast review.',
      createdAt: 'Yesterday · 2:15 PM',
      issueId: 'issue-growth',
    },
  ],
  meetings: [
    {
      id: 'meeting-leadership-current',
      teamId: 'leadership',
      label: 'Leadership L10',
      dateLabel: 'Monday · 9:00 AM',
      status: 'upcoming',
      facilitatorId: 'ava-khan',
      attendeeIds: ['ava-khan', 'marcus-lee', 'priya-shah', 'daniel-cho'],
      lastRating: 8.8,
      agendaProgress: 0,
      agendaTotal: 7,
      idsSolved: 1,
      idsTotal: 3,
      recap: 'Bring the onboarding handoff decision to IDS and leave with one clear owner.',
    },
    {
      id: 'meeting-delivery-current',
      teamId: 'delivery',
      label: 'Delivery L10',
      dateLabel: 'Tuesday · 10:30 AM',
      status: 'upcoming',
      facilitatorId: 'maria-ortiz',
      attendeeIds: ['maria-ortiz'],
      lastRating: 8.4,
      agendaProgress: 0,
      agendaTotal: 7,
      idsSolved: 0,
      idsTotal: 1,
      recap: 'Review the kickoff pilot and solve scope visibility.',
    },
    {
      id: 'meeting-growth-current',
      teamId: 'growth',
      label: 'Growth L10',
      dateLabel: 'Wednesday · 11:00 AM',
      status: 'upcoming',
      facilitatorId: 'jon-bell',
      attendeeIds: ['jon-bell'],
      lastRating: 9.1,
      agendaProgress: 0,
      agendaTotal: 7,
      idsSolved: 0,
      idsTotal: 1,
      recap: 'Align on qualified pipeline definitions before forecast review.',
    },
  ],
  activity: [
    {
      id: 'activity-1',
      actorId: 'priya-shah',
      action: 'added a headline',
      target: 'Aster renewed for another year',
      time: 'Today · 8:20 AM',
      type: 'meeting',
    },
    {
      id: 'activity-2',
      actorId: 'ava-khan',
      action: 'updated a Rock',
      target: 'Client onboarding playbook',
      time: 'Yesterday · 4:42 PM',
      type: 'rock',
    },
    {
      id: 'activity-3',
      actorId: 'daniel-cho',
      action: 'completed a To-Do',
      target: 'Confirm Azure cost alerts',
      time: 'Yesterday · 2:18 PM',
      type: 'todo',
    },
    {
      id: 'activity-4',
      actorId: 'marcus-lee',
      action: 'raised an Issue',
      target: 'Quarterly planning template',
      time: 'Fri · 11:03 AM',
      type: 'issue',
    },
  ],
};
